# Generated by Django 3.2.4 on 2021-08-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cidade',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True)),
                ('cnpj', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.cidade')),
                ('tradicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.pais')),
            ],
            options={
                'db_table': 'restaurante',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RestauranteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante')),
            ],
            options={
                'db_table': 'restCard',
            },
        ),
    ]
