# Generated by Django 3.2.4 on 2021-08-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('thumb', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('carr', models.CharField(default='', max_length=100)),
                ('igrd', models.CharField(default='', max_length=100)),
                ('istr', models.CharField(default='', max_length=100)),
                ('culinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.pais')),
            ],
        ),
    ]
