# Generated by Django 3.2.4 on 2021-08-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='carr',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='igrd',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='istr',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='thumb',
        ),
        migrations.CreateModel(
            name='ReceitaPag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carr', models.CharField(default='carr_dummy.txt', max_length=100)),
                ('igrd', models.CharField(default='igrd_lorem.txt', max_length=100)),
                ('istr', models.CharField(default='istr_lorem.txt', max_length=100)),
                ('rect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'db_table': 'receitaPag',
            },
        ),
        migrations.CreateModel(
            name='ReceitaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(default='dummy.png', max_length=100)),
                ('desc', models.CharField(default='lorem.txt', max_length=100)),
                ('rect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'db_table': 'receitaCard',
            },
        ),
    ]
